config/routes.rb
Coconut::Application.routes.draw do
  match '/flights/:flight_id/seats'=> 'seats#flight_seats' ,via:[:get,:post]

  resources :seats

  resources :flights

end

app/models/flight.rb
class Flight < ActiveRecord::Base
  has_many :seats
end

app/models/seat.rb
class Seat < ActiveRecord::Base
  belongs_to :flight
  validate :baggage_does_not_exceed_baggage_capacity,:seats_available
  def baggage_does_not_exceed_baggage_capacity
    if baggage > flight.baggage_allowance
      errors.add(:baggage,"You have too much baggage")
    end
  end
  def seats_available
    if flight.seats.size >= flight.capacity
     errors.add(:flight_id,"The flight is fully booked")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :set_flight, only: [:show, :edit, :update, :destroy]

  # GET /flights
  # GET /flights.json
  def index
    @flights = Flight.all
  end

  # GET /flights/1
  # GET /flights/1.json
  def show
  end

  # GET /flights/new
  def new
    @flight = Flight.new
  end

  # GET /flights/1/edit
  def edit
  end

  # POST /flights
  # POST /flights.json
  def create
    @flight = Flight.new(flight_params)

    respond_to do |format|
      if @flight.save
        format.html { redirect_to @flight, notice: 'Flight was successfully created.' }
        format.json { render action: 'show', status: :created, location: @flight }
      else
        format.html { render action: 'new' }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flights/1
  # PATCH/PUT /flights/1.json
  def update
    respond_to do |format|
      if @flight.update(flight_params)
        format.html { redirect_to @flight, notice: 'Flight was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flights/1
  # DELETE /flights/1.json
  def destroy
    @flight.destroy
    respond_to do |format|
      format.html { redirect_to flights_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flight
      @flight = Flight.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flight_params
      params.require(:flight).permit(:departure, :arrival, :destination, :baggage_allowance, :capacity)
    end
end

app/controllers/seats_controller.rb
class SeatsController < ApplicationController
  before_action :set_seat, only: [:show, :edit, :update, :destroy]

  # GET /seats
  # GET /seats.json
  def index
    @seats = Seat.all
  end

  # GET /seats/1
  # GET /seats/1.json
  def show
  end

  # GET /seats/new
  def new
    @seat = Seat.new
  end

  # GET /seats/1/edit
  def edit
  end

  # POST /seats
  # POST /seats.json
  def create
    @seat = Seat.new(seat_params)

    respond_to do |format|
      if @seat.save
        format.html { redirect_to @seat, notice: 'Seat was successfully created.' }
        format.json { render action: 'show', status: :created, location: @seat }
        format.js
      else
        format.html { render action: 'new' }
        format.json { render json: @seat.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /seats/1
  # PATCH/PUT /seats/1.json
  def update
    respond_to do |format|
      if @seat.update(seat_params)
        format.html { redirect_to @seat, notice: 'Seat was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @seat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seats/1
  # DELETE /seats/1.json
  def destroy
    @seat.destroy
    respond_to do |format|
      format.html { redirect_to seats_url }
      format.json { head :no_content }
      format.js
    end
  end

  #
  def flight_seats
    @flight = Flight.find (params[:flight_id])
    respond_to do |format|
      format.js
    end
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_seat
      @seat = Seat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def seat_params
      params.require(:seat).permit(:flight_id, :name, :baggage)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/seats_helper.rb
module SeatsHelper
end

app/views/flights/_form.html.erb
<%= form_for(@flight) do |f| %>
  <% if @flight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

      <ul>
      <% @flight.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :departure %><br>
    <%= f.datetime_select :departure %>
  </div>
  <div class="field">
    <%= f.label :arrival %><br>
    <%= f.datetime_select :arrival %>
  </div>
  <div class="field">
    <%= f.label :destination %><br>
    <%= f.text_field :destination %>
  </div>
  <div class="field">
    <%= f.label :baggage_allowance %><br>
    <%= f.text_field :baggage_allowance %>
  </div>
  <div class="field">
    <%= f.label :capacity %><br>
    <%= f.number_field :capacity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/flights/_new_seat.html.erb
<h1>New seat</h1>

<%= form_for(seat) do |f| %>
  <% if seat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(seat.errors.count, "error") %> prohibited this seat from being saved:</h2>

      <ul>
      <% seat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :flight_id %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :baggage %><br />
    <%= f.text_field :baggage %>
  </div>
  <div class="actions">
    <%= f.submit "Create"%>
  </div>
<% end %>

app/views/flights/_seat_list.html.erb
<h1>Listing seats</h1>

<table>
  <thead>
    <tr>
      <th>Flight</th>
      <th>Name</th>
      <th>Baggage</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% seats.each do |seat| %>
      <tr>
        <td><%= seat.name %></td>
        <td><%= seat.baggage %></td>
        <td><%= link_to 'Show', seat %></td>
        <td><%= link_to 'Edit', edit_seat_path(seat) %></td>
        <td><%= link_to 'Destroy', seat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/flights/edit.html.erb
<h1>Editing flight</h1>

<%= render 'form' %>

<%= link_to 'Show', @flight %> |
<%= link_to 'Back', flights_path %>

app/views/flights/flight_seats.js.erb
$("#seats").html("<%= escape_javascript( render :partial => '/flights/seat_list', :locals =>{:seats=>@flight.seats}) %>");

app/views/flights/index.html.erb
<h1>Listing flights</h1>

<table>
  <thead>
    <tr>
      <th>Departure</th>
      <th>Arrival</th>
      <th>Destination</th>
      <th>Baggage allowance</th>
      <th>Capacity</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @flights.each do |flight| %>
      <tr>
        <td><%= flight.departure %></td>
        <td><%= flight.arrival %></td>
        <td><%= flight.destination %></td>
        <td><%= flight.baggage_allowance %></td>
        <td><%= flight.capacity %></td>
        <td><%= link_to 'Show', flight %></td>
        <td><%= link_to 'Edit', edit_flight_path(flight) %></td>
        <td><%= link_to 'Destroy', flight, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Flight', new_flight_path %>

app/views/flights/new.html.erb
<h1>New flight</h1>

<%= render 'form' %>

<%= link_to 'Back', flights_path %>

app/views/flights/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Departure:</strong>
  <%= @flight.departure %>
</p>

<p>
  <strong>Arrival:</strong>
  <%= @flight.arrival %>
</p>

<p>
  <strong>Destination:</strong>
  <%= @flight.destination %>
</p>

<p>
  <strong>Baggage allowance:</strong>
  <%= @flight.baggage_allowance %>
</p>

<p>
  <strong>Capacity:</strong>
  <%= @flight.capacity %>
</p>

<div id="seats">
  <%= render :partial=>"seat_list", :locals=>{:seats=>@flight.seats} %>
</div>

<%= link_to "Refresh seats", "/flights/#{@flight.id}/seats", :remote => true %>

<button onclick="myFunction()">Try it</button>

<script>
function myFunction()
{
<%= render :partial=>"seat_list", :locals=>{:seats=>@flight.seats} %>
}
</script>

<%= render :partial=>"new_seat", :locals=>{:seat=>Seat.new(:flight_id=>@flight.id)} %>

<%= link_to 'Edit', edit_flight_path(@flight) %> |
<%= link_to 'Back', flights_path %>

app/views/flights/show.js.erb
$("#seats").html("<%= escape_javascript render(@seat) %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Coconut</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/seats/_form.html.erb
<%= form_for(@seat) do |f| %>
  <% if @seat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@seat.errors.count, "error") %> prohibited this seat from being saved:</h2>

      <ul>
      <% @seat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :flight_id %><br>
    <%= f.number_field :flight_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :baggage %><br>
    <%= f.text_field :baggage %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/seats/create.js.erb
$("#seats").html("<%= escape_javascript( render :partial => '/flights/seat_list', :locals =>{:seats=>@flight.seats}) %>");
$('#flash').html("<%= escape_javascript raw(flash_display) %>");
$('html, body').delay(700).animate({scrollTop:0}, 900);
$("#success").html("Ticked Booked Successfully!!").delay(2400).toggle(showOrHide);

app/views/seats/edit.html.erb
<h1>Editing seat</h1>

<%= render 'form' %>

<%= link_to 'Show', @seat %> |
<%= link_to 'Back', seats_path %>

app/views/seats/flight_seats.js.erb
$("#seats").html("<%= escape_javascript( render :partial => '/flights/seat_list', :locals =>{:seats=>@flight.seats}) %>");

app/views/seats/index.html.erb
<h1>Listing seats</h1>

<table>
  <thead>
    <tr>
      <th>Flight</th>
      <th>Name</th>
      <th>Baggage</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @seats.each do |seat| %>
      <tr>
        <td><%= seat.flight_id %></td>
        <td><%= seat.name %></td>
        <td><%= seat.baggage %></td>
        <td><%= link_to 'Show', seat %></td>
        <td><%= link_to 'Edit', edit_seat_path(seat) %></td>
        <td><%= link_to 'Destroy', seat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Seat', new_seat_path %>

app/views/seats/new.html.erb
<h1>New seat</h1>

<%= render 'form' %>

<%= link_to 'Back', seats_path %>

app/views/seats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Flight:</strong>
  <%= @seat.flight_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @seat.name %>
</p>

<p>
  <strong>Baggage:</strong>
  <%= @seat.baggage %>
</p>

<%= link_to 'Edit', edit_seat_path(@seat) %> |
<%= link_to 'Back', seats_path %>